import { PostStatus } from "@prisma/client";
import { generateText, Output } from "ai";
import { createOpenAI } from "@ai-sdk/openai";
import { z } from "zod";

import { getMessages } from "@/features/i18n/get-messages";
import { getAiProviderByValue } from "@/lib/ai/provider-registry";
import { recordObservabilityEvent } from "@/lib/analytics";
import { generatedArticleSectionOrder } from "@/lib/content/article-structure";
import { detectDuplicateEquipmentPost } from "@/lib/generation/duplicates";
import { generationStageOrder, generationTerminalStageIds } from "@/lib/generation/stages";
import { buildMarkdownFromStructuredArticle, buildHtmlFromStructuredArticle } from "@/lib/markdown";
import { createCanonicalEquipmentIdentity, normalizeDisplayText } from "@/lib/normalization";
import { buildVerifiedResearchPayload } from "@/lib/research";
import { buildSeoPayload } from "@/lib/seo";

import { getFixtureByNormalizedEquipmentName } from "./fixture-data";
import {
  findFallbackProviderConfig,
  formatProviderConfigLabel,
  getProviderConfigById,
  resolveProviderApiKey,
} from "./provider-configs";

export { generatedArticleSectionOrder };

export const promptTemplatePurposeOrder = Object.freeze([
  "system_instruction",
  "data_grounding",
  "output_json_structure",
  "article_formatting",
  "safety_boundaries",
]);

export const savePromptTemplatesSchema = z.object({
  templates: z
    .array(
      z
        .object({
          id: z.string().trim().min(1),
          isActive: z.boolean(),
          name: z.string().trim().min(1),
          purpose: z.enum(promptTemplatePurposeOrder),
          systemPrompt: z.string().trim().min(1),
          userPromptTemplate: z.string().trim().min(1),
        })
        .strict(),
    )
    .min(1),
});

export class AiCompositionError extends Error {
  constructor(message, { details = null, status = "ai_composition_error", statusCode = 500 } = {}) {
    super(message);
    this.name = "AiCompositionError";
    this.details = details;
    this.status = status;
    this.statusCode = statusCode;
  }
}

function dedupeStrings(values) {
  return [...new Set((values || []).map((value) => `${value}`.trim()).filter(Boolean))];
}

function collapseWhitespace(value) {
  return `${value || ""}`.trim().replace(/\s+/g, " ");
}

function compareAlphabetical(left, right) {
  return left.localeCompare(right, undefined, {
    sensitivity: "base",
  });
}

function toSerializableJson(value) {
  return JSON.parse(JSON.stringify(value));
}

function truncateErrorMessage(value, maxLength = 280) {
  const normalizedValue = collapseWhitespace(value);

  if (!normalizedValue || normalizedValue.length <= maxLength) {
    return normalizedValue;
  }

  return `${normalizedValue.slice(0, maxLength - 3).trimEnd()}...`;
}

function redactSecrets(value) {
  const normalizedValue = `${value || ""}`;

  return normalizedValue
    .replace(/\b(sk|rk|pk|local|sess|key)-[a-zA-Z0-9._-]{8,}\b/g, "[redacted-secret]")
    .replace(/\b[a-zA-Z0-9]{12,}_[a-zA-Z0-9._-]{12,}\b/g, "[redacted-secret]");
}

function chunkList(values, count) {
  return values.slice(0, count);
}

const readerFacingDisclosureRules = Object.freeze([
  {
    label: "AI authorship disclosure",
    pattern:
      /\b(ai-generated|ai generated|generated by ai|written by ai|compiled by ai|created by ai|produced by ai|generated with ai|created with ai|compiled with ai)\b/i,
  },
  {
    label: "AI terminology",
    pattern: /\b(artificial intelligence|large language model|language model|llm)\b/i,
  },
  {
    label: "self-referential authorship wording",
    pattern:
      /\b(this|the)\s+(article|post|guide|content|text)\s+(was|is|has been)\s+(generated|created|compiled|produced|drafted|composed)\b|\b(this|the)\s+(article|post|guide|content|text)\s+(was|is|has been)\s+written\s+(by|with|using)\b/i,
  },
  {
    label: "internal workflow wording",
    pattern:
      /\b(research payload|research bundle|evidence bundle|verified research package|acceptance fixture|synthesized orientation layer|stable learning sequence|machine-readable)\b/i,
  },
]);

function isRecord(value) {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

function tryParseErrorRecord(value) {
  if (typeof value !== "string") {
    return null;
  }

  const trimmedValue = value.trim();

  if (!trimmedValue.startsWith("{")) {
    return null;
  }

  try {
    const parsedValue = JSON.parse(trimmedValue);

    return isRecord(parsedValue) ? parsedValue : null;
  } catch {
    return null;
  }
}

function getNestedValue(record, path) {
  return path.split(".").reduce((currentValue, segment) => {
    if (!isRecord(currentValue)) {
      return undefined;
    }

    return currentValue[segment];
  }, record);
}

function getFirstMatchingValue(records, paths) {
  for (const record of records) {
    for (const path of paths) {
      const value = getNestedValue(record, path);

      if (value !== undefined && value !== null && value !== "") {
        return value;
      }
    }
  }

  return null;
}

function normalizeStatusCode(value) {
  if (typeof value === "number" && Number.isInteger(value) && value >= 100 && value <= 599) {
    return value;
  }

  if (typeof value === "string" && /^\d{3}$/.test(value.trim())) {
    return Number(value);
  }

  return null;
}

function buildProviderErrorContext(providerConfig) {
  const providerMetadata = getAiProviderByValue(providerConfig?.provider);

  return {
    model: providerConfig?.model || null,
    provider: providerConfig?.provider || null,
    providerConfigId: providerConfig?.id || null,
    providerLabel: providerMetadata?.label || providerConfig?.provider || null,
  };
}

function collectErrorRecords(error) {
  const records = [];
  const seenRecords = new Set();

  function addRecord(value) {
    if (!isRecord(value) || seenRecords.has(value)) {
      return;
    }

    seenRecords.add(value);
    records.push(value);
  }

  addRecord(error);

  if (!isRecord(error)) {
    return records;
  }

  addRecord(error.error);
  addRecord(error.details);
  addRecord(error.body);
  addRecord(tryParseErrorRecord(error.body));
  addRecord(error.response);
  addRecord(error.response?.data);
  addRecord(error.response?.body);
  addRecord(tryParseErrorRecord(error.response?.body));
  addRecord(error.response?.error);
  addRecord(tryParseErrorRecord(error.responseBody));
  addRecord(error.cause);
  addRecord(error.cause?.error);
  addRecord(error.cause?.details);
  addRecord(error.cause?.body);
  addRecord(tryParseErrorRecord(error.cause?.body));
  addRecord(error.cause?.response);
  addRecord(error.cause?.response?.data);
  addRecord(error.cause?.response?.body);
  addRecord(tryParseErrorRecord(error.cause?.response?.body));
  addRecord(error.cause?.response?.error);
  addRecord(tryParseErrorRecord(error.cause?.responseBody));

  return records;
}

function extractProviderFailureMetadata(error, providerConfig) {
  const records = collectErrorRecords(error);
  const fallbackMessage = error instanceof Error ? error.message : `${error}`;
  const rawMessage = truncateErrorMessage(
    redactSecrets(
      getFirstMatchingValue(records, ["message", "error.message", "details.message"]) || fallbackMessage,
    ),
  );
  const providerMessage = truncateErrorMessage(
    redactSecrets(
      getFirstMatchingValue(records, [
        "error.message",
        "message",
        "details.message",
        "data.error.message",
        "data.message",
      ]) || rawMessage,
    ),
  );
  const providerStatusCode =
    normalizeStatusCode(getFirstMatchingValue(records, ["statusCode", "status", "response.status"])) ||
    normalizeStatusCode(isRecord(error) ? error.response?.status : null);
  const providerCodeValue = getFirstMatchingValue(records, [
    "error.code",
    "code",
    "details.code",
    "data.error.code",
    "data.code",
  ]);
  const providerTypeValue = getFirstMatchingValue(records, [
    "error.type",
    "type",
    "details.type",
    "data.error.type",
    "data.type",
  ]);
  const providerParamValue = getFirstMatchingValue(records, [
    "error.param",
    "param",
    "details.param",
    "data.error.param",
    "data.param",
  ]);
  const requestIdValue = getFirstMatchingValue(records, [
    "request_id",
    "requestId",
    "headers.x-request-id",
    "headers.request-id",
  ]);

  return {
    ...buildProviderErrorContext(providerConfig),
    providerCode: providerCodeValue === null ? null : collapseWhitespace(providerCodeValue),
    providerMessage,
    providerParam: providerParamValue === null ? null : collapseWhitespace(providerParamValue),
    providerStatusCode,
    providerType: providerTypeValue === null ? null : collapseWhitespace(providerTypeValue),
    rawMessage,
    requestId: requestIdValue === null ? null : collapseWhitespace(requestIdValue),
  };
}

function classifyProviderFailure(metadata) {
  const combinedMessage = collapseWhitespace(
    [
      metadata.providerMessage,
      metadata.rawMessage,
      metadata.providerCode,
      metadata.providerType,
      metadata.providerParam,
    ]
      .filter(Boolean)
      .join(" "),
  ).toLowerCase();
  const normalizedCode = `${metadata.providerCode || ""}`.trim().toLowerCase();
  const timeoutCodes = ["ABORT_ERR", "ECONNABORTED", "ESOCKETTIMEDOUT", "ETIMEDOUT", "UND_ERR_CONNECT_TIMEOUT"];

  if (
    (/\bmodel\b/.test(combinedMessage) &&
      /(not found|unknown|unavailable|not available|unsupported|does not exist|deprecated|decommissioned|not enabled|access denied|permission)/.test(
        combinedMessage,
      )) ||
    /(invalid_model|model_not_found|model_not_available|unknown_model|unsupported_model)/.test(
      normalizedCode,
    )
  ) {
    return "model_unavailable";
  }

  if (
    metadata.providerStatusCode === 429 ||
    /(rate limit|too many requests|quota|insufficient_quota|resource exhausted|requests per minute|tokens per minute)/.test(
      combinedMessage,
    ) ||
    /(insufficient_quota|quota_exceeded|rate_limit|resource_exhausted|too_many_requests)/.test(
      normalizedCode,
    )
  ) {
    return "rate_limited";
  }

  if (
    timeoutCodes.includes(`${metadata.providerCode || ""}`.trim().toUpperCase()) ||
    /(deadline exceeded|timed out|timeout|connect timeout|read timeout|request aborted|request timed out)/.test(
      combinedMessage,
    )
  ) {
    return "timeout";
  }

  if (
    /(fetch failed|network|socket hang up|connection reset|connection refused|getaddrinfo|dns|econnrefused|econnreset|enotfound|ehostunreach)/.test(
      combinedMessage,
    )
  ) {
    return "network_error";
  }

  if (
    metadata.providerStatusCode === 401 ||
    metadata.providerStatusCode === 403 ||
    /(invalid api key|incorrect api key|authentication|unauthorized|forbidden|permission denied|invalid x-api-key|api key not valid)/.test(
      combinedMessage,
    ) ||
    /(authentication_error|invalid_api_key|permission_denied|unauthorized|forbidden)/.test(
      normalizedCode,
    )
  ) {
    return "authentication_failed";
  }

  if (
    (metadata.providerStatusCode && metadata.providerStatusCode >= 500) ||
    /(internal server error|service unavailable|bad gateway|gateway timeout|temporarily unavailable|overloaded|server error|try again later)/.test(
      combinedMessage,
    )
  ) {
    return "server_error";
  }

  if (
    metadata.providerStatusCode === 400 ||
    metadata.providerStatusCode === 404 ||
    metadata.providerStatusCode === 422 ||
    /(invalid request|bad request|unsupported parameter|maximum context length|context length|prompt too long|input too long|malformed|unprocessable|content policy|invalid schema|too many tokens|max tokens)/.test(
      combinedMessage,
    )
  ) {
    return "request_rejected";
  }

  return "request_failed";
}

function getProviderFailureStatus(kind, providerStatusCode) {
  const safeStatusCode =
    providerStatusCode && providerStatusCode >= 400 && providerStatusCode <= 599
      ? providerStatusCode
      : null;

  if (kind === "authentication_failed") {
    return {
      status: "provider_authentication_failed",
      statusCode: safeStatusCode || 401,
    };
  }

  if (kind === "model_unavailable") {
    return {
      status: "provider_model_unavailable",
      statusCode: safeStatusCode || 400,
    };
  }

  if (kind === "rate_limited") {
    return {
      status: "provider_rate_limited",
      statusCode: safeStatusCode || 429,
    };
  }

  if (kind === "timeout") {
    return {
      status: "provider_timeout",
      statusCode: safeStatusCode || 504,
    };
  }

  if (kind === "network_error") {
    return {
      status: "provider_network_error",
      statusCode: safeStatusCode || 503,
    };
  }

  if (kind === "server_error") {
    return {
      status: "provider_server_error",
      statusCode: safeStatusCode || 502,
    };
  }

  if (kind === "request_rejected") {
    return {
      status: "provider_request_rejected",
      statusCode: safeStatusCode || 400,
    };
  }

  return {
    status: "provider_request_failed",
    statusCode: safeStatusCode || 502,
  };
}

function hasMeaningfulProviderMessage(message) {
  const normalizedMessage = collapseWhitespace(message).toLowerCase();

  if (!normalizedMessage) {
    return false;
  }

  return !["error", "fetch failed", "request failed", "unexpected error", "unknown error"].includes(
    normalizedMessage,
  );
}

function createProviderFailureMessage(providerConfig, metadata, failureKind) {
  const providerConfigLabel = formatProviderConfigLabel(providerConfig);
  let message = `${providerConfigLabel} failed during draft generation.`;

  if (failureKind === "authentication_failed") {
    message = `${providerConfigLabel} rejected the request because the credentials were not accepted.`;
  } else if (failureKind === "model_unavailable") {
    message = `${providerConfigLabel} is not available for the configured account or endpoint.`;
  } else if (failureKind === "rate_limited") {
    message = `${providerConfigLabel} temporarily rejected the request because the provider rate limit or quota was reached.`;
  } else if (failureKind === "timeout") {
    message = `${providerConfigLabel} did not respond in time.`;
  } else if (failureKind === "network_error") {
    message = `The request to ${providerConfigLabel} could not reach the provider service.`;
  } else if (failureKind === "server_error") {
    message = `${providerConfigLabel} returned a provider-side error.`;
  } else if (failureKind === "request_rejected") {
    message = `${providerConfigLabel} rejected the generation request.`;
  }

  if (hasMeaningfulProviderMessage(metadata.providerMessage)) {
    const normalizedMessage = collapseWhitespace(message).toLowerCase();
    const normalizedProviderMessage = collapseWhitespace(metadata.providerMessage).toLowerCase();

    if (!normalizedMessage.includes(normalizedProviderMessage)) {
      return `${message} Provider message: ${metadata.providerMessage}`;
    }
  }

  return message;
}

function ensureProviderScopedMessage(message, providerConfig) {
  const providerConfigLabel = formatProviderConfigLabel(providerConfig);
  const normalizedMessage = collapseWhitespace(message);

  if (!providerConfigLabel || !normalizedMessage) {
    return normalizedMessage;
  }

  if (normalizedMessage.toLowerCase().startsWith(providerConfigLabel.toLowerCase())) {
    return normalizedMessage;
  }

  return `${providerConfigLabel}: ${normalizedMessage}`;
}

function normalizeProviderCompositionError(error, providerConfig) {
  const providerContext = buildProviderErrorContext(providerConfig);

  if (error instanceof AiCompositionError) {
    if (error.status === "invalid_provider_credentials" || error.status.startsWith("provider_")) {
      return new AiCompositionError(ensureProviderScopedMessage(error.message, providerConfig), {
        details: {
          ...providerContext,
          ...(error.details || {}),
        },
        status: error.status,
        statusCode: error.statusCode,
      });
    }

    return new AiCompositionError(
      `${formatProviderConfigLabel(providerConfig)} returned an invalid draft payload: ${error.message}`,
      {
        details: {
          ...providerContext,
          ...(error.details || {}),
          providerMessage: truncateErrorMessage(error.message),
        },
        status: "provider_response_invalid",
        statusCode: 502,
      },
    );
  }

  const metadata = extractProviderFailureMetadata(error, providerConfig);
  const failureKind = classifyProviderFailure(metadata);
  const failureStatus = getProviderFailureStatus(failureKind, metadata.providerStatusCode);

  return new AiCompositionError(createProviderFailureMessage(providerConfig, metadata, failureKind), {
    details: {
      ...metadata,
      failureKind,
    },
    status: failureStatus.status,
    statusCode: failureStatus.statusCode,
  });
}

function renderTemplate(template, variables) {
  return template.replace(/\{\{\s*([a-zA-Z0-9_]+)\s*\}\}/g, (_, key) => {
    const value = variables[key];

    if (value === undefined || value === null) {
      return "";
    }

    return `${value}`;
  });
}

async function resolvePrismaClient(prisma) {
  if (prisma) {
    return prisma;
  }

  const { getPrismaClient } = await import("@/lib/prisma");

  return getPrismaClient();
}

function createPromptTemplateSummary(template) {
  return {
    id: template.id,
    isActive: template.isActive,
    name: template.name,
    purpose: template.purpose,
    systemPrompt: template.systemPrompt,
    updatedAt: template.updatedAt instanceof Date ? template.updatedAt.toISOString() : null,
    userPromptTemplate: template.userPromptTemplate,
    version: template.version,
  };
}

function selectActivePromptTemplates(templates) {
  const activeTemplatesByPurpose = new Map();

  for (const purpose of promptTemplatePurposeOrder) {
    const activeTemplate = templates
      .filter((template) => template.purpose === purpose && template.isActive)
      .sort((left, right) => right.version - left.version)[0];

    if (!activeTemplate) {
      throw new AiCompositionError(`An active prompt template is required for "${purpose}".`, {
        status: "missing_prompt_template",
        statusCode: 500,
      });
    }

    activeTemplatesByPurpose.set(purpose, activeTemplate);
  }

  return promptTemplatePurposeOrder.map((purpose) => activeTemplatesByPurpose.get(purpose));
}

export async function getPromptConfigurationSnapshot(prisma) {
  const db = await resolvePrismaClient(prisma);
  const templates = await db.promptTemplate.findMany({
    orderBy: [{ purpose: "asc" }, { version: "desc" }],
    select: {
      id: true,
      isActive: true,
      name: true,
      purpose: true,
      systemPrompt: true,
      updatedAt: true,
      userPromptTemplate: true,
      version: true,
    },
  });

  return {
    summary: {
      activeTemplateCount: templates.filter((template) => template.isActive).length,
      purposeCount: new Set(templates.map((template) => template.purpose)).size,
      templateCount: templates.length,
    },
    templates: templates.map(createPromptTemplateSummary),
  };
}

export async function savePromptTemplates(input, options = {}, prisma) {
  const parsedInput = savePromptTemplatesSchema.parse(input);
  const db = await resolvePrismaClient(prisma);

  for (const purpose of promptTemplatePurposeOrder) {
    const hasActiveTemplate = parsedInput.templates.some(
      (template) => template.isActive && template.purpose === purpose,
    );

    if (!hasActiveTemplate) {
      throw new AiCompositionError(`At least one active prompt template is required for "${purpose}".`, {
        status: "missing_prompt_template",
        statusCode: 400,
      });
    }
  }

  await db.$transaction(async (tx) => {
    for (const template of parsedInput.templates) {
      await tx.promptTemplate.update({
        where: {
          id: template.id,
        },
        data: {
          isActive: template.isActive,
          name: template.name,
          systemPrompt: template.systemPrompt,
          userPromptTemplate: template.userPromptTemplate,
        },
      });
    }

    if (options.actorId) {
      await tx.auditEvent.create({
        data: {
          action: "PROMPT_TEMPLATE_UPDATED",
          actorId: options.actorId,
          entityId: "prompt_template_collection",
          entityType: "prompt_template",
          payloadJson: {
            templates: parsedInput.templates.map((template) => ({
              id: template.id,
              isActive: template.isActive,
            })),
          },
        },
      });
    }
  });

  return {
    snapshot: await getPromptConfigurationSnapshot(db),
  };
}

export async function loadActivePromptLayers(prisma) {
  const db = await resolvePrismaClient(prisma);
  const templates = await db.promptTemplate.findMany({
    orderBy: [{ purpose: "asc" }, { version: "desc" }],
    select: {
      id: true,
      isActive: true,
      name: true,
      purpose: true,
      systemPrompt: true,
      userPromptTemplate: true,
      version: true,
    },
  });

  return selectActivePromptTemplates(templates);
}

function getGenerationModeProfile(articleDepth) {
  if (articleDepth === "fast") {
    return {
      faqCount: 3,
      overviewSentenceCount: 2,
      sectionDetailLevel: "concise",
      sectionIntroTone: "concise",
    };
  }

  if (articleDepth === "repair") {
    return {
      faqCount: 4,
      overviewSentenceCount: 3,
      sectionDetailLevel: "detailed",
      sectionIntroTone: "troubleshooting",
    };
  }

  if (articleDepth === "maintenance") {
    return {
      faqCount: 4,
      overviewSentenceCount: 3,
      sectionDetailLevel: "detailed",
      sectionIntroTone: "maintenance",
    };
  }

  return {
    faqCount: 6,
    overviewSentenceCount: 6,
    sectionDetailLevel: "comprehensive",
    sectionIntroTone: "complete",
  };
}

function getResearchComplexityProfile(researchPayload) {
  const componentCount = researchPayload.components?.length || 0;
  const variantCount = researchPayload.variants?.length || 0;
  const useCount = researchPayload.uses?.length || 0;
  const manufacturerCount = researchPayload.manufacturers?.length || 0;
  const modelCount = researchPayload.manufacturers?.reduce(
    (count, manufacturer) => count + (manufacturer.models?.length || 0),
    0,
  ) || 0;
  const faultCount = researchPayload.faults?.length || 0;
  const maintenanceTaskCount = researchPayload.maintenanceTasks?.length || 0;
  const manualCount = researchPayload.manuals?.length || 0;
  const mediaCount = researchPayload.mediaCandidates?.length || 0;
  const complexityScore =
    componentCount +
    variantCount +
    useCount +
    manufacturerCount +
    modelCount +
    faultCount +
    maintenanceTaskCount +
    manualCount +
    Math.min(mediaCount, 3);
  let tier = "standard";

  if (complexityScore >= 26) {
    tier = "advanced";
  } else if (complexityScore >= 14) {
    tier = "intermediate";
  }

  return {
    complexityScore,
    componentCount,
    faultCount,
    maintenanceTaskCount,
    manualCount,
    manufacturerCount,
    mediaCount,
    modelCount,
    tier,
    useCount,
    variantCount,
  };
}

function getAdaptiveGenerationProfile(articleDepth, researchPayload) {
  const baseProfile = getGenerationModeProfile(articleDepth);
  const complexityProfile = getResearchComplexityProfile(researchPayload);
  const detailBonus =
    complexityProfile.tier === "advanced" ? 2 : complexityProfile.tier === "intermediate" ? 1 : 0;

  return {
    ...baseProfile,
    complexity: complexityProfile,
    faqCount:
      articleDepth === "fast" ? baseProfile.faqCount : Math.min(baseProfile.faqCount + detailBonus, 8),
    overviewSentenceCount:
      articleDepth === "fast"
        ? baseProfile.overviewSentenceCount
        : Math.min(baseProfile.overviewSentenceCount + detailBonus * 2, 10),
  };
}

function createVisualGuideSection(id, title, intro, images = []) {
  if (!images.length) {
    return null;
  }

  return createSection(id, title, {
    images,
    intro,
    kind: "image_gallery",
    sourceReferenceIds: collectSourceReferenceIds(images),
  });
}

function takeAffinitizedImages(images, sectionId, fallbackCount = 0, fallbackState = null) {
  const matchedImages = (images || []).filter((image) => image?.sectionAffinity?.includes(sectionId));

  if (matchedImages.length) {
    return matchedImages;
  }

  if (!fallbackCount || !fallbackState) {
    return [];
  }

  const fallbackImages = [];

  for (const image of images || []) {
    const fallbackKey = image?.sourceUrl || image?.publicUrl || image?.url || image?.alt || null;

    if (!fallbackKey || fallbackState.usedKeys.has(fallbackKey)) {
      continue;
    }

    fallbackState.usedKeys.add(fallbackKey);
    fallbackImages.push(image);

    if (fallbackImages.length >= fallbackCount) {
      break;
    }
  }

  return fallbackImages;
}

function buildVisualGuideSections(researchPayload, request) {
  if (!request.includeImages) {
    return {};
  }

  const images = [...(researchPayload.mediaCandidates || [])];
  const fallbackState = {
    usedKeys: new Set(),
  };
  const featuredImages = takeAffinitizedImages(images, "featured_image", 1, fallbackState);
  const operationImages = takeAffinitizedImages(images, "operation_visual_guide", 1, fallbackState);
  const componentsImages = takeAffinitizedImages(images, "components_visual_guide", 1, fallbackState);
  const modelImages = takeAffinitizedImages(images, "model_visual_guide", 2, fallbackState);
  const workflowImages = takeAffinitizedImages(images, "workflow_visual_guide", images.length, fallbackState);

  return {
    componentsVisualGuideSection: createVisualGuideSection(
      "components_visual_guide",
      "Components visual guide",
      "These illustrations help readers connect major assemblies to the component descriptions so the hardware layout is easier to picture while reading.",
      componentsImages,
    ),
    featuredImageSection: featuredImages.length
      ? createVisualGuideSection(
          "featured_image",
          "Featured image",
          "The lead visual frames the equipment as a complete working system before the article moves into operation, maintenance, and troubleshooting detail.",
          featuredImages,
        )
      : null,
    modelVisualGuideSection: createVisualGuideSection(
      "model_visual_guide",
      "Model visual guide",
      "These visuals add concrete examples of the equipment family so readers can connect model names to recognizable real-world configurations.",
      modelImages,
    ),
    operationVisualGuideSection: createVisualGuideSection(
      "operation_visual_guide",
      "Operation visual guide",
      "Operation-focused visuals show the parts of the system that matter most during setup, image formation, and live use.",
      operationImages,
    ),
    workflowVisualGuideSection: createVisualGuideSection(
      "workflow_visual_guide",
      "Workflow visual guide",
      "Workflow visuals support the procedural sections by illustrating handling, display, or room-level context that affects safe use.",
      workflowImages,
    ),
  };
}

function getSectionAffinitizedImages(researchPayload, sectionIds = []) {
  const requestedSectionIds = Array.isArray(sectionIds) ? sectionIds.filter(Boolean) : [];
  const images = [...(researchPayload.mediaCandidates || [])];

  if (!requestedSectionIds.length) {
    return images;
  }

  const matchedImages = images.filter((image) =>
    requestedSectionIds.some((sectionId) => image?.sectionAffinity?.includes(sectionId)),
  );

  return matchedImages.length ? matchedImages : images;
}

function attachIllustrationsToEntries(entries = [], images = [], maxImagesPerEntry = 1) {
  if (!Array.isArray(entries) || !entries.length || !Array.isArray(images) || !images.length || maxImagesPerEntry < 1) {
    return entries;
  }

  return entries.map((entry, index) => {
    const assignedImages = [];

    for (let imageOffset = 0; imageOffset < maxImagesPerEntry; imageOffset += 1) {
      const candidate = images[(index + imageOffset) % images.length];

      if (candidate) {
        assignedImages.push(candidate);
      }
    }

    return {
      ...entry,
      images: assignedImages,
    };
  });
}

function formatAudienceLabel(audience) {
  return audience.replace(/_/g, " ");
}

function buildPromptVariables({
  article,
  articleDepth,
  disclaimer,
  equipmentName,
  locale,
  researchPayload,
  targetAudience,
}) {
  return {
    articleDepth,
    articleJson: article ? JSON.stringify(article, null, 2) : "",
    equipmentName,
    locale,
    researchPayloadJson: JSON.stringify(researchPayload, null, 2),
    sectionOrderJson: JSON.stringify(generatedArticleSectionOrder, null, 2),
    targetAudienceList: targetAudience.map(formatAudienceLabel).join(", "),
    disclaimer,
  };
}

function buildPromptBundle({ article, promptLayers, request, researchPayload, disclaimer }) {
  const variables = buildPromptVariables({
    article,
    articleDepth: request.articleDepth,
    disclaimer,
    equipmentName: request.equipmentName,
    locale: request.locale,
    researchPayload,
    targetAudience: request.targetAudience,
  });

  return promptLayers.map((layer) => ({
    id: layer.id,
    name: layer.name,
    purpose: layer.purpose,
    renderedSystemPrompt: renderTemplate(layer.systemPrompt, variables),
    renderedUserPrompt: renderTemplate(layer.userPromptTemplate, variables),
    version: layer.version,
  }));
}

function createSection(id, title, payload) {
  return {
    id,
    title,
    ...payload,
  };
}

function collectSourceReferenceIds(entries) {
  return dedupeStrings(
    (entries || []).flatMap((entry) => entry?.sourceReferenceIds || []),
  );
}

function pushArticleSnippet(snippets, label, value) {
  const text = collapseWhitespace(value);

  if (text) {
    snippets.push({
      label,
      text,
    });
  }
}

function collectReaderFacingArticleSnippets(article) {
  const snippets = [];

  pushArticleSnippet(snippets, "title", article?.title);
  pushArticleSnippet(snippets, "excerpt", article?.excerpt);

  for (const [index, item] of (article?.faq || []).entries()) {
    pushArticleSnippet(snippets, `faq[${index}].question`, item?.question);
    pushArticleSnippet(snippets, `faq[${index}].answer`, item?.answer);
  }

  for (const [sectionIndex, section] of (article?.sections || []).entries()) {
    pushArticleSnippet(snippets, `sections[${sectionIndex}].intro`, section?.intro);

    if (section?.kind === "image_gallery") {
      for (const [imageIndex, image] of (section.images || []).entries()) {
        pushArticleSnippet(
          snippets,
          `sections[${sectionIndex}].images[${imageIndex}].caption`,
          image?.caption,
        );
      }

      continue;
    }

    if (section?.kind === "text") {
      for (const [paragraphIndex, paragraph] of (section.paragraphs || []).entries()) {
        pushArticleSnippet(
          snippets,
          `sections[${sectionIndex}].paragraphs[${paragraphIndex}]`,
          paragraph,
        );
      }

      continue;
    }

    if (section?.kind === "list") {
      for (const [itemIndex, item] of (section.items || []).entries()) {
        pushArticleSnippet(snippets, `sections[${sectionIndex}].items[${itemIndex}].title`, item?.title);
        pushArticleSnippet(
          snippets,
          `sections[${sectionIndex}].items[${itemIndex}].description`,
          item?.description,
        );
      }

      continue;
    }

    if (section?.kind === "models_by_manufacturer") {
      for (const [groupIndex, group] of (section.groups || []).entries()) {
        for (const [modelIndex, model] of (group.models || []).entries()) {
          pushArticleSnippet(
            snippets,
            `sections[${sectionIndex}].groups[${groupIndex}].models[${modelIndex}].summary`,
            model?.summary,
          );
        }
      }

      continue;
    }

    if (section?.kind === "faults") {
      for (const [itemIndex, item] of (section.items || []).entries()) {
        pushArticleSnippet(snippets, `sections[${sectionIndex}].items[${itemIndex}].title`, item?.title);
        pushArticleSnippet(snippets, `sections[${sectionIndex}].items[${itemIndex}].cause`, item?.cause);
        pushArticleSnippet(snippets, `sections[${sectionIndex}].items[${itemIndex}].symptoms`, item?.symptoms);
        pushArticleSnippet(snippets, `sections[${sectionIndex}].items[${itemIndex}].remedy`, item?.remedy);
      }

      continue;
    }

    if (section?.kind === "steps") {
      for (const [stepIndex, step] of (section.steps || []).entries()) {
        pushArticleSnippet(snippets, `sections[${sectionIndex}].steps[${stepIndex}].title`, step?.title);
        pushArticleSnippet(
          snippets,
          `sections[${sectionIndex}].steps[${stepIndex}].description`,
          step?.description,
        );
      }

      continue;
    }

    if (section?.kind === "faq") {
      for (const [itemIndex, item] of (section.items || []).entries()) {
        pushArticleSnippet(
          snippets,
          `sections[${sectionIndex}].items[${itemIndex}].question`,
          item?.question,
        );
        pushArticleSnippet(
          snippets,
          `sections[${sectionIndex}].items[${itemIndex}].answer`,
          item?.answer,
        );
      }
    }
  }

  return snippets;
}

function assertNoReaderFacingDisclosure(article) {
  const snippets = collectReaderFacingArticleSnippets(article);

  for (const snippet of snippets) {
    for (const rule of readerFacingDisclosureRules) {
      const match = snippet.text.match(rule.pattern);

      if (match) {
        throw new AiCompositionError(
          `Published-facing text must not mention AI generation or internal composition workflow. Found ${rule.label} in ${snippet.label}: "${match[0]}".`,
          {
            details: {
              field: snippet.label,
              matchedText: match[0],
              rule: rule.label,
            },
            status: "invalid_generated_draft",
            statusCode: 500,
          },
        );
      }
    }
  }
}

function buildOverviewParagraphs(researchPayload, request) {
  const profile = getAdaptiveGenerationProfile(request.articleDepth, researchPayload);
  const audiences = request.targetAudience.map(formatAudienceLabel).join(", ");
  const paragraphs = [
    researchPayload.definition?.summary ||
      `${request.equipmentName} is described here using the most reliable reference material currently available.`,
    researchPayload.operatingPrinciple?.summary || "",
    `This guide is written for ${audiences} and highlights the operating, maintenance, and safety points most relevant to that audience.`,
  ].filter(Boolean);

  if (profile.sectionIntroTone === "troubleshooting") {
    paragraphs.push(
      "Troubleshooting and recovery actions are emphasized so that the guide remains practical for service-oriented review.",
    );
  }

  if (profile.sectionIntroTone === "maintenance") {
    paragraphs.push(
      "Preventive care, cleaning discipline, and safe inspection routines are emphasized to support equipment reliability.",
    );
  }

  if (researchPayload.components.length) {
    paragraphs.push(
      `${request.equipmentName} is explained through ${researchPayload.components.length} core component${
        researchPayload.components.length === 1 ? "" : "s"
      } so readers can connect each part to its role in normal operation.`,
    );
  }

  if (researchPayload.variants.length) {
    paragraphs.push(
      `Where the evidence supports it, the guide also distinguishes ${researchPayload.variants.length} major variant${
        researchPayload.variants.length === 1 ? "" : "s"
      } so differences in setup, handling, or application stay visible.`,
    );
  }

  if (researchPayload.uses.length) {
    paragraphs.push(
      `Use-case coverage stays practical by linking the equipment to ${researchPayload.uses.length} verified application area${
        researchPayload.uses.length === 1 ? "" : "s"
      }, rather than treating the device as a purely abstract concept.`,
    );
  }

  if (researchPayload.maintenanceTasks.length || researchPayload.safetyPrecautions.length) {
    paragraphs.push(
      "Maintenance and safety sections explain not only what to do, but also why each step matters for reliability, operator safety, and service escalation.",
    );
  }

  if (profile.sectionDetailLevel === "comprehensive") {
    if (researchPayload.manufacturers.length) {
      paragraphs.push(
        `Manufacturer and model coverage is included where the sources support it, so the article can connect general equipment principles to real product families used in practice.`,
      );
    }

    if (researchPayload.manuals.length) {
      paragraphs.push(
        "Manual and reference coverage stays visible throughout the article so readers can move from plain-language explanation to the source documents used to ground each section.",
      );
    }
  }

  if (profile.complexity.tier === "advanced") {
    paragraphs.push(
      `Because ${request.equipmentName} combines multiple subsystems, this article treats it as a coordinated platform rather than a single isolated device, with attention to imaging, accessories, maintenance, and workflow dependencies.`,
    );
  }

  return chunkList(paragraphs, profile.overviewSentenceCount);
}

function buildPrincipleOfOperationParagraphs(researchPayload, request) {
  const profile = getAdaptiveGenerationProfile(request.articleDepth, researchPayload);
  const paragraphs = [
    researchPayload.operatingPrinciple?.summary ||
      "The available references did not fully describe the operating principle for this equipment type.",
    "For exact controls, configurations, and model-specific behavior, follow the official operator guide for the unit in use.",
  ];

  if (profile.complexity.componentCount >= 5) {
    paragraphs.push(
      "In practice, the operating principle depends on the coordinated performance of optics or sensing hardware, signal processing, user controls, and the supporting accessories that keep the procedure or workflow stable.",
    );
  }

  if (profile.complexity.faultCount >= 3) {
    paragraphs.push(
      "That is why troubleshooting should be approached as a system-level exercise: image, motion, control, power, and accessory failures can each distort the final output in different ways.",
    );
  }

  return paragraphs;
}

function buildExpertSectionDescription(entityName, description, complexityTier, emphasis) {
  const normalizedDescription = collapseWhitespace(description);

  if (!normalizedDescription) {
    return entityName;
  }

  if (complexityTier !== "advanced") {
    return normalizedDescription;
  }

  return `${normalizedDescription} ${emphasis}`;
}

function buildManufacturersSection(researchPayload) {
  return createSection("commonly_used_manufacturers", "Commonly used manufacturers", {
    intro:
      "Manufacturers are listed when supported by the available references for this equipment category. The list is illustrative rather than a definitive worldwide ranking.",
    items: attachIllustrationsToEntries(
      researchPayload.manufacturers.map((manufacturer) => ({
        description: [
          manufacturer.primaryDomain,
          manufacturer.headquartersCountry ? `Headquarters: ${manufacturer.headquartersCountry}` : null,
          manufacturer.branchCountries?.length
            ? `Verified branch countries: ${manufacturer.branchCountries.join(", ")}`
            : null,
        ]
          .filter(Boolean)
          .join(" | "),
        sourceReferenceIds: manufacturer.sourceReferenceIds,
        title: manufacturer.name,
      })),
      getSectionAffinitizedImages(researchPayload, ["featured_image", "model_visual_guide"]),
    ),
    kind: "list",
    sourceReferenceIds: collectSourceReferenceIds(researchPayload.manufacturers),
  });
}

function buildModelsSection(researchPayload) {
  return createSection("commonly_encountered_models", "Commonly encountered models", {
    groups: researchPayload.manufacturers
      .filter((manufacturer) => manufacturer.models?.length)
      .map((manufacturer) => ({
        manufacturer: manufacturer.name,
        models: attachIllustrationsToEntries(
          manufacturer.models.map((model) => ({
            latestKnownYear: model.latestKnownYear,
            name: model.name,
            sourceReferenceIds: model.sourceReferenceIds,
            summary: model.summary,
          })),
          getSectionAffinitizedImages(researchPayload, ["model_visual_guide", "components_visual_guide"]),
        ),
    })),
    kind: "models_by_manufacturer",
    sourceReferenceIds: collectSourceReferenceIds(
      researchPayload.manufacturers.flatMap((manufacturer) => manufacturer.models || []),
    ),
  });
}

function buildFaultsSection(researchPayload) {
  return createSection("faults_and_remedies", "Faults and remedies", {
    intro:
      "Common faults are summarized with their likely causes, visible symptoms, and first-line remedies so the troubleshooting path stays concrete and source-grounded.",
    items: attachIllustrationsToEntries(
      researchPayload.faults.map((fault) => ({
        cause: fault.cause,
        evidenceCount: fault.sourceReferenceIds?.length || 0,
        remedy: fault.remedy,
        severity: fault.severity,
        sourceReferenceIds: fault.sourceReferenceIds,
        symptoms: fault.symptoms,
        title: fault.title,
      })),
      getSectionAffinitizedImages(researchPayload, ["operation_visual_guide", "workflow_visual_guide"]),
    ),
    kind: "faults",
    sourceReferenceIds: collectSourceReferenceIds(researchPayload.faults),
  });
}

function splitMaintenanceTasks(researchPayload) {
  const dailyTasks = [];
  const scheduledTasks = [];

  for (const task of researchPayload.maintenanceTasks || []) {
    const frequency = `${task.frequency || ""} ${task.label || ""} ${task.details || ""}`
      .toLowerCase();

    if (frequency.includes("daily") || frequency.includes("pre-use") || frequency.includes("before each")) {
      dailyTasks.push(task);
      continue;
    }

    scheduledTasks.push(task);
  }

  if (!dailyTasks.length && scheduledTasks.length) {
    dailyTasks.push(...scheduledTasks.slice(0, Math.min(2, scheduledTasks.length)));
  }

  return {
    dailyTasks,
    scheduledTasks: scheduledTasks.length ? scheduledTasks : dailyTasks,
  };
}

function buildMaintenanceSections(researchPayload) {
  const { dailyTasks, scheduledTasks } = splitMaintenanceTasks(researchPayload);
  const maintenanceIllustrations = getSectionAffinitizedImages(researchPayload, [
    "workflow_visual_guide",
    "components_visual_guide",
  ]);

  return [
    createSection("daily_care_and_maintenance", "Daily care and maintenance", {
      intro:
        "Daily care tasks should be completed consistently so the optical path stays clean and the instrument is ready for the next verified workflow.",
      items: attachIllustrationsToEntries(
        dailyTasks.map((task) => ({
          description: task.details || "",
          frequency: task.frequency || null,
          sourceReferenceIds: task.sourceReferenceIds,
          title: task.label,
        })),
        maintenanceIllustrations,
      ),
      kind: "list",
      sourceReferenceIds: collectSourceReferenceIds(dailyTasks),
    }),
    createSection("preventive_maintenance_schedule", "Preventive maintenance schedule", {
      intro:
        "Preventive maintenance intervals should follow the operator guide, service notes, and institutional biomedical engineering policy.",
      items: attachIllustrationsToEntries(
        scheduledTasks.map((task) => ({
          description: task.details
            ? `${task.details}${task.frequency ? ` (${task.frequency})` : ""}`
            : task.frequency || task.label,
          frequency: task.frequency || null,
          sourceReferenceIds: task.sourceReferenceIds,
          title: task.label,
        })),
        maintenanceIllustrations,
      ),
      kind: "list",
      sourceReferenceIds: collectSourceReferenceIds(scheduledTasks),
    }),
  ];
}

function buildSopSection(researchPayload, fixture) {
  const modelDifferenceNote = researchPayload.manufacturers
    .flatMap((manufacturer) => manufacturer.models || [])
    .slice(0, 2)
    .map((model) => `${model.name}: ${model.summary || "follow the manufacturer-specific operator guide."}`);

  return createSection("sop_and_how_to_use_guidance", "SOP and how-to-use guidance", {
    intro:
      "These SOP-style steps summarize the verified workflow and should always be checked against the official operator manual for the exact model in use.",
    kind: "steps",
    sourceReferenceIds: collectSourceReferenceIds([
      researchPayload.operatingPrinciple || {},
      ...(researchPayload.safetyPrecautions || []),
      ...(researchPayload.maintenanceTasks || []),
    ]),
    steps: attachIllustrationsToEntries(
      [
        ...((fixture?.compositionNotes?.howToUseSteps || []).length
          ? fixture.compositionNotes.howToUseSteps
          : [
              {
                description:
                  "Confirm the device is clean, safe to energize, connected correctly, and prepared according to the official operating instructions before use.",
                title: "Prepare the equipment",
              },
              {
                description:
                  "Follow the manufacturer workflow step by step, checking controls, patient or specimen positioning, operating indicators, and any model-specific adjustments as you proceed.",
                title: "Operate using the approved workflow",
              },
              {
                description:
                  "Shut the equipment down safely, complete cleaning or reset steps, and record any abnormal findings, maintenance needs, or service escalations before the next use.",
                title: "Close out and document the session",
              },
            ]),
        ...(modelDifferenceNote.length
          ? [
              {
                description: modelDifferenceNote.join(" "),
                title: "Apply model-specific differences inline",
              },
            ]
          : []),
      ],
      getSectionAffinitizedImages(researchPayload, ["workflow_visual_guide", "operation_visual_guide"]),
    ),
  });
}

function buildFaqSection(researchPayload, request) {
  const profile = getAdaptiveGenerationProfile(request.articleDepth, researchPayload);
  const equipmentLabel = normalizeDisplayText(request.equipmentName) || researchPayload.equipment.name || "this equipment";
  const faqItems = [
    {
      answer:
        researchPayload.definition?.summary ||
        `${equipmentLabel} is used according to the verified references summarized in this guide.`,
      question: `What is ${/^[aeiou]/i.test(equipmentLabel) ? "an" : "a"} ${equipmentLabel.toLowerCase()} used for?`,
    },
    {
      answer:
        researchPayload.operatingPrinciple?.summary ||
        `${equipmentLabel} works according to the verified operating principle summarized in this guide.`,
      question: `How does ${/^[aeiou]/i.test(equipmentLabel) ? "an" : "a"} ${equipmentLabel.toLowerCase()} work?`,
    },
    {
      answer:
        researchPayload.faults?.[0]?.remedy ||
        "Start with cleaning, illumination checks, and low-power refocusing before escalating to service review.",
      question: "What should I do first if the image is unclear?",
    },
    {
      answer:
        "Daily cleaning of optical surfaces and scheduled preventive maintenance reduce unexpected failures and image-quality drift.",
      question: `Why is routine ${equipmentLabel.toLowerCase()} maintenance important?`,
    },
    {
      answer:
        "Use only the model-specific operator manual, approved cleaning materials, and institutional biomedical engineering procedures for deeper service actions.",
      question: "Which documents should staff follow before maintenance or repair?",
    },
    {
      answer:
        profile.complexity.tier === "advanced"
          ? "Complex equipment should be interpreted as an integrated system, so image quality, accessories, maintenance condition, and procedural setup all need to be reviewed together rather than in isolation."
          : "Read the equipment as a complete working system so setup, operation, and maintenance decisions stay connected.",
      question: `How should complex ${equipmentLabel.toLowerCase()} systems be assessed?`,
    },
    {
      answer:
        researchPayload.safetyPrecautions?.[0]?.details ||
        "Safety guidance should be read before use so transport, energizing, cleaning, and shutdown steps do not damage the equipment or create avoidable risk.",
      question: "Why are the safety precautions described in detail?",
    },
  ];

  return createSection("faq", "FAQ", {
    items: chunkList(faqItems, profile.faqCount),
    kind: "faq",
    sourceReferenceIds: collectSourceReferenceIds([
      researchPayload.definition || {},
      researchPayload.operatingPrinciple || {},
      ...(researchPayload.faults || []),
      ...(researchPayload.manuals || []),
      ...(researchPayload.maintenanceTasks || []),
    ]),
  });
}

function buildReferencesSection(researchPayload) {
  return createSection("references", "References", {
    items: researchPayload.sourceReferences.map((reference) => ({
      accessStatus: reference.accessStatus,
      fileType: reference.fileType,
      language: reference.language,
      lastCheckedAt: reference.lastCheckedAt,
      notes: reference.notes,
      sourceType: reference.sourceType,
      sourceReferenceIds: reference.id ? [reference.id] : [],
      title: reference.title,
      url: reference.url,
    })),
    kind: "references",
    sourceReferenceIds: researchPayload.sourceReferences.map((reference) => reference.id),
  });
}

function buildDisclaimerSection(disclaimer) {
  return createSection("disclaimer", "Disclaimer", {
    kind: "text",
    paragraphs: [disclaimer],
    sourceReferenceIds: [],
  });
}

function buildStructuredArticle({ disclaimer, fixture, providerConfig, request, researchPayload }) {
  const equipmentTitle = normalizeDisplayText(request.equipmentName) || researchPayload.equipment.name;
  const profile = getAdaptiveGenerationProfile(request.articleDepth, researchPayload);
  const visualGuideSections = buildVisualGuideSections(researchPayload, request);
  const title =
    request.articleDepth === "repair"
      ? `${equipmentTitle}: Troubleshooting, Faults, Maintenance, and Manuals`
      : request.articleDepth === "maintenance"
        ? `${equipmentTitle}: Care, Maintenance, Safety, and Manuals`
        : `${equipmentTitle}: Definition, Operation, Maintenance, Faults, and Manuals`;
  const excerpt = [
    researchPayload.definition?.summary,
    request.articleDepth === "fast"
      ? "This concise guide focuses on core operation, care, and safety points, with references for deeper follow-up."
      : profile.sectionDetailLevel === "comprehensive"
        ? `This detailed guide explains how the equipment works, what its major parts do, where it is used, how to maintain it, which faults are commonly encountered, and which references or manuals support those points${profile.complexity.tier === "advanced" ? ", while treating the equipment as a multi-subsystem clinical platform rather than a simple standalone device" : ""}.`
        : "This guide covers definition, operation, maintenance, common faults, and supporting manuals while keeping safety notes and references easy to review.",
  ]
    .filter(Boolean)
    .join(" ");
  const componentIllustrations = getSectionAffinitizedImages(researchPayload, [
    "components_visual_guide",
    "operation_visual_guide",
  ]);
  const variantIllustrations = getSectionAffinitizedImages(researchPayload, [
    "model_visual_guide",
    "workflow_visual_guide",
  ]);
  const useCaseIllustrations = getSectionAffinitizedImages(researchPayload, [
    "workflow_visual_guide",
    "operation_visual_guide",
    "featured_image",
  ]);
  const baseSections = [
    ...(visualGuideSections.featuredImageSection ? [visualGuideSections.featuredImageSection] : []),
    createSection("definition_and_overview", "Definition and overview", {
      kind: "text",
      paragraphs: buildOverviewParagraphs(researchPayload, request),
      sourceReferenceIds: collectSourceReferenceIds([researchPayload.definition]),
    }),
    createSection("principle_of_operation", "Principle of operation", {
      kind: "text",
      paragraphs: buildPrincipleOfOperationParagraphs(researchPayload, request),
      sourceReferenceIds: collectSourceReferenceIds([researchPayload.operatingPrinciple]),
    }),
    ...(visualGuideSections.operationVisualGuideSection
      ? [visualGuideSections.operationVisualGuideSection]
      : []),
    createSection("components_and_parts", "Components and parts", {
      intro:
        "Component descriptions focus on what each part contributes to normal operation so the device can be understood as a working system instead of a list of names.",
      kind: "list",
      items: attachIllustrationsToEntries(
        researchPayload.components.map((component) => ({
          description: buildExpertSectionDescription(
            component.label,
            component.details || component.label,
            profile.complexity.tier,
            "In expert review, this part is assessed in terms of how its condition changes image quality, control response, safety, or serviceability across the full system.",
          ),
          sourceReferenceIds: component.sourceReferenceIds,
          title: component.label,
        })),
        componentIllustrations,
      ),
      sourceReferenceIds: collectSourceReferenceIds(researchPayload.components),
    }),
    ...(visualGuideSections.componentsVisualGuideSection
      ? [visualGuideSections.componentsVisualGuideSection]
      : []),
    createSection("types_and_variants", "Types and variants", {
      intro:
        "Variant coverage highlights the practical differences that affect setup, viewing, workflow, or expected use context.",
      kind: "list",
      items: attachIllustrationsToEntries(
        researchPayload.variants.map((variant) => ({
          description: buildExpertSectionDescription(
            variant.label,
            variant.details || variant.label,
            profile.complexity.tier,
            "Those differences matter because they change what operators, technicians, and support teams need to watch during setup and use.",
          ),
          sourceReferenceIds: variant.sourceReferenceIds,
          title: variant.label,
        })),
        variantIllustrations,
      ),
      sourceReferenceIds: collectSourceReferenceIds(researchPayload.variants),
    }),
    createSection("uses_and_applications", "Uses and applications", {
      intro:
        "Applications are described in concrete workflow terms so readers can connect the equipment to real clinical, laboratory, teaching, or service contexts.",
      kind: "list",
      items: attachIllustrationsToEntries(
        researchPayload.uses.map((useCase) => ({
          description: buildExpertSectionDescription(
            useCase.label,
            useCase.details || useCase.label,
            profile.complexity.tier,
            "That workflow context helps explain why configuration choices, accessory readiness, and maintenance discipline directly affect outcomes.",
          ),
          sourceReferenceIds: useCase.sourceReferenceIds,
          title: useCase.label,
        })),
        useCaseIllustrations,
      ),
      sourceReferenceIds: collectSourceReferenceIds(researchPayload.uses),
    }),
  ];
  const optionalSections = [];

  if (request.includeManufacturers && researchPayload.manufacturers.length) {
    optionalSections.push(buildManufacturersSection(researchPayload));
  }

  if (request.includeModels && researchPayload.manufacturers.some((manufacturer) => manufacturer.models?.length)) {
    optionalSections.push(buildModelsSection(researchPayload));
    if (visualGuideSections.modelVisualGuideSection) {
      optionalSections.push(visualGuideSections.modelVisualGuideSection);
    }
  }

  if (request.includeFaults && researchPayload.faults.length) {
    optionalSections.push(buildFaultsSection(researchPayload));
  }

  optionalSections.push(...buildMaintenanceSections(researchPayload));
  optionalSections.push(
    createSection("safety_precautions", "Safety precautions", {
      intro:
        "These precautions are intentionally explicit so handling, cleaning, adjustment, and shutdown risks remain visible while reading the operational guidance.",
      kind: "list",
      items: researchPayload.safetyPrecautions.map((precaution) => ({
        description: precaution.details || precaution.label,
        sourceReferenceIds: precaution.sourceReferenceIds,
        title: precaution.label,
      })),
      sourceReferenceIds: collectSourceReferenceIds(researchPayload.safetyPrecautions),
    }),
  );
  optionalSections.push(buildSopSection(researchPayload, fixture));
  if (visualGuideSections.workflowVisualGuideSection) {
    optionalSections.push(visualGuideSections.workflowVisualGuideSection);
  }

  if (request.includeManualLinks && researchPayload.manuals.length) {
    optionalSections.push(
      createSection("manuals_and_technical_documents", "Manuals and technical documents", {
        intro:
          "These documents anchor the article to operator, service, or maintenance material that readers can consult for the exact model in use.",
        items: researchPayload.manuals.map((manual) => ({
          accessStatus: manual.accessStatus,
          fileType: manual.fileType,
          language: manual.language,
          lastCheckedAt: manual.lastCheckedAt,
          notes: manual.notes,
          sourceReferenceIds: manual.sourceReferenceIds,
          title: manual.title,
          url: manual.url,
        })),
        kind: "manuals",
        sourceReferenceIds: collectSourceReferenceIds(researchPayload.manuals),
      }),
    );
  }

  optionalSections.push(buildFaqSection(researchPayload, request));
  optionalSections.push(buildReferencesSection(researchPayload));
  optionalSections.push(buildDisclaimerSection(disclaimer));

  return {
    disclaimer,
    equipmentAliases: researchPayload.equipment.aliases,
    equipmentName: researchPayload.equipment.name,
    excerpt,
    faq: buildFaqSection(researchPayload, request).items,
    generationContext: {
      articleDepth: request.articleDepth,
      locale: request.locale,
      provider: providerConfig.provider,
      providerConfigId: providerConfig.id,
      targetAudience: request.targetAudience,
    },
    relatedKeywords: fixture?.compositionNotes?.relatedKeywords || [researchPayload.equipment.name],
    sections: [...baseSections, ...optionalSections],
    slug: researchPayload.equipment.slug,
    structuredBlocks: {
      faq: buildFaqSection(researchPayload, request).items,
      faults: researchPayload.faults,
      maintenanceTasks: researchPayload.maintenanceTasks,
      models: researchPayload.manufacturers.flatMap((manufacturer) =>
        (manufacturer.models || []).map((model) => ({
          ...model,
          manufacturerName: manufacturer.name,
        })),
      ),
    },
    title,
  };
}

function validateStructuredArticle(article) {
  const sectionIds = article.sections.map((section) => section.id);

  for (const requiredId of [
    "definition_and_overview",
    "principle_of_operation",
    "daily_care_and_maintenance",
    "references",
    "disclaimer",
  ]) {
    if (!sectionIds.includes(requiredId)) {
      throw new AiCompositionError(`Generated draft is missing the "${requiredId}" section.`, {
        status: "invalid_generated_draft",
        statusCode: 500,
      });
    }
  }

  if (!article.title?.trim()) {
    throw new AiCompositionError("Generated draft title is required.", {
      status: "invalid_generated_draft",
      statusCode: 500,
    });
  }

  const orderedIds = [...sectionIds].sort(
    (left, right) =>
      generatedArticleSectionOrder.indexOf(left) - generatedArticleSectionOrder.indexOf(right),
  );

  if (orderedIds.join("|") !== sectionIds.join("|")) {
    throw new AiCompositionError("Generated sections are out of the required order.", {
      status: "invalid_generated_section_order",
      statusCode: 500,
    });
  }

  const manufacturersSection = article.sections.find(
    (section) => section.id === "commonly_used_manufacturers",
  );

  if (manufacturersSection) {
    const manufacturerTitles = manufacturersSection.items.map((item) => item.title);

    if (new Set(manufacturerTitles).size !== manufacturerTitles.length) {
      throw new AiCompositionError("Generated manufacturers section contains duplicate rows.", {
        status: "invalid_generated_draft",
        statusCode: 500,
      });
    }
  }

  const modelsSection = article.sections.find(
    (section) => section.id === "commonly_encountered_models",
  );

  if (modelsSection && modelsSection.groups.some((group) => !group.models.length)) {
    throw new AiCompositionError("Generated model groups must not be empty.", {
      status: "invalid_generated_draft",
      statusCode: 500,
    });
  }

  assertNoReaderFacingDisclosure(article);
}

const faqItemSchema = z.object({
  answer: z.string().trim().min(1),
  question: z.string().trim().min(1),
});

const articleSectionSchema = z.object({
  id: z.string().trim().min(1),
  title: z.string().trim().min(1),
}).passthrough();

const generatedArticleSchema = z.object({
  disclaimer: z.string().trim().min(1),
  equipmentAliases: z.array(z.string().trim()).default([]),
  equipmentName: z.string().trim().min(1),
  excerpt: z.string().trim().min(1),
  faq: z.array(faqItemSchema).default([]),
  generationContext: z.object({
    articleDepth: z.string().trim().min(1),
    locale: z.string().trim().min(1),
    provider: z.string().trim().min(1),
    providerConfigId: z.string().trim().min(1),
    targetAudience: z.array(z.string().trim().min(1)).default([]),
  }).passthrough(),
  relatedKeywords: z.array(z.string().trim().min(1)).default([]),
  sections: z.array(articleSectionSchema).min(1),
  slug: z.string().trim().min(1),
  structuredBlocks: z.object({
    faq: z.array(faqItemSchema).default([]),
    faults: z.array(z.object({}).passthrough()).default([]),
    maintenanceTasks: z.array(z.object({}).passthrough()).default([]),
    models: z.array(z.object({}).passthrough()).default([]),
  }).passthrough(),
  title: z.string().trim().min(1),
}).passthrough();

function sortStructuredArticleSections(sections) {
  return [...sections].sort((left, right) => {
    const leftIndex = generatedArticleSectionOrder.indexOf(left.id);
    const rightIndex = generatedArticleSectionOrder.indexOf(right.id);
    const normalizedLeftIndex = leftIndex === -1 ? Number.MAX_SAFE_INTEGER : leftIndex;
    const normalizedRightIndex = rightIndex === -1 ? Number.MAX_SAFE_INTEGER : rightIndex;

    if (normalizedLeftIndex !== normalizedRightIndex) {
      return normalizedLeftIndex - normalizedRightIndex;
    }

    return left.id.localeCompare(right.id, undefined, {
      sensitivity: "base",
    });
  });
}

function normalizeGeneratedArticle(article, { disclaimer, providerConfig, request }) {
  const parsedArticle = generatedArticleSchema.parse(article);
  const normalizedFaq = parsedArticle.faq.length
    ? parsedArticle.faq
    : parsedArticle.structuredBlocks?.faq || [];

  return {
    ...parsedArticle,
    disclaimer,
    equipmentAliases: dedupeStrings(parsedArticle.equipmentAliases || []),
    equipmentName: normalizeDisplayText(parsedArticle.equipmentName) || request.equipmentName,
    faq: normalizedFaq,
    generationContext: {
      ...parsedArticle.generationContext,
      articleDepth: request.articleDepth,
      locale: request.locale,
      provider: providerConfig.provider,
      providerConfigId: providerConfig.id,
      targetAudience: request.targetAudience,
    },
    relatedKeywords: dedupeStrings(parsedArticle.relatedKeywords || [request.equipmentName]),
    sections: sortStructuredArticleSections(parsedArticle.sections || []),
    slug: createCanonicalEquipmentIdentity(parsedArticle.equipmentName || request.equipmentName).slug,
    structuredBlocks: {
      ...(parsedArticle.structuredBlocks || {}),
      faq: normalizedFaq,
      faults: parsedArticle.structuredBlocks?.faults || [],
      maintenanceTasks: parsedArticle.structuredBlocks?.maintenanceTasks || [],
      models: parsedArticle.structuredBlocks?.models || [],
    },
    title: normalizeDisplayText(parsedArticle.title) || request.equipmentName,
  };
}

async function composeStructuredArticleWithOpenAiSdk({
  promptBundle,
  providerApiKey,
  providerConfig,
  request,
  researchPayload,
}) {
  const openai = createOpenAI({
    apiKey: providerApiKey,
  });
  const system = promptBundle.map((layer) => layer.renderedSystemPrompt).filter(Boolean).join("\n\n");
  const prompt = [
    ...promptBundle.map((layer) => layer.renderedUserPrompt).filter(Boolean),
    [
      "Return a complete structured article object that satisfies the provided schema expectations.",
      `Use "${request.equipmentName}" as the target equipment name.`,
      `Write like a domain expert for ${request.equipmentName}, with the judgment of a specialist who understands operation, maintenance, troubleshooting, and the practical differences between models or subsystems.`,
      "Do not hardcode microscope-specific content unless the requested equipment is actually a microscope.",
      `Keep sections in this order when present: ${generatedArticleSectionOrder.join(", ")}.`,
      "Always include the required sections: definition_and_overview, principle_of_operation, daily_care_and_maintenance, references, disclaimer.",
      "structuredBlocks.faq must match faq.",
      "Use empty arrays instead of invented references when verified references are unavailable.",
      "Default to detailed, educational explanations that unpack how parts, workflow steps, maintenance tasks, and fault patterns relate to one another.",
      "When evidence exists, prefer fully populated sections over skeletal ones and explain the rationale behind safety, maintenance, and troubleshooting guidance.",
      "For text sections, write multi-paragraph explanations instead of single-sentence summaries unless the requested article depth is explicitly fast.",
      `Scale the length and depth of the article to the equipment complexity. This request has approximately ${
        getResearchComplexityProfile(researchPayload).complexityScore
      } complexity points across components, models, faults, maintenance tasks, manuals, and visuals.`,
      "If there are multiple subsystems or workflow dependencies, explain how they interact instead of describing each part in isolation.",
      "When images are available, use as many relevant illustrative photos or trusted linked photo resources as the verified media set permits.",
      "Distribute visuals across featured, operation, components, model, and workflow image-gallery sections instead of concentrating everything in a single image block.",
      "Prefer official manufacturer, product, documentation, distributor, or clearly attributable editorial image sources, and preserve attribution, links, and license cues when provided.",
      "Write in a natural editorial voice that reads like a normal published equipment guide.",
      "Do not mention AI, automation, prompts, models, research payloads, internal workflows, or that the article was generated, drafted, compiled, or composed.",
      "If supporting evidence is missing, omit the claim or state the limitation plainly without referring to the generation process.",
    ].join("\n"),
  ].join("\n\n");

  const result = await generateText({
    model: openai(providerConfig.model),
    output: Output.object({
      schema: generatedArticleSchema,
    }),
    prompt,
    system,
  });

  return {
    executionMode: "ai_sdk_object",
    structuredArticle: normalizeGeneratedArticle(result.output, {
      disclaimer: request.disclaimer || "",
      providerConfig,
      request,
    }),
  };
}

function createProvider(providerConfig, options = {}) {
  if (!getAiProviderByValue(providerConfig.provider)) {
    throw new AiCompositionError(
      `Provider "${providerConfig.provider}" is not supported by the composition pipeline.`,
      {
        status: "unsupported_provider",
        statusCode: 400,
      },
    );
  }

  return {
    apiKeySource: "stored",
    model: providerConfig.model,
    name: providerConfig.provider,
    async composeStructuredArticle(context) {
      if (typeof options.composeStructuredArticle === "function") {
        const resolvedCredential = resolveProviderApiKey(providerConfig);

        return options.composeStructuredArticle({
          ...context,
          apiKeySource: resolvedCredential.source,
          providerApiKey: resolvedCredential.apiKey,
        });
      }

      if (options.useDeterministicFixture === true) {
        return {
          executionMode: "deterministic_fixture",
          structuredArticle: buildStructuredArticle(context),
        };
      }

      if (providerConfig.provider !== "openai") {
        throw new AiCompositionError(
          `Provider "${providerConfig.provider}" is not yet wired to the AI SDK generation runtime.`,
          {
            status: "unsupported_provider",
            statusCode: 400,
          },
        );
      }

      const resolvedCredential = resolveProviderApiKey(providerConfig);

      if (!resolvedCredential.apiKey) {
        throw new AiCompositionError(
          `Provider configuration "${providerConfig.id}" is missing a stored API key. Save one from the Providers admin page before generating drafts.`,
          {
            status: "invalid_provider_credentials",
            statusCode: 400,
          },
        );
      }

      return composeStructuredArticleWithOpenAiSdk({
        ...context,
        providerApiKey: resolvedCredential.apiKey,
      });
    },
  };
}

async function resolveProviderConfig(providerConfigId, prisma) {
  const providerConfig = await getProviderConfigById(providerConfigId, prisma);

  if (!providerConfig || !providerConfig.isEnabled) {
    throw new AiCompositionError(
      `Provider configuration "${providerConfigId}" is not available for generation.`,
      {
        status: "invalid_provider_config",
        statusCode: 400,
      },
    );
  }

  return providerConfig;
}

function createProviderFallbackWarning(primaryProviderConfig, fallbackProviderConfig, error) {
  const reason = error instanceof Error ? error.message : `${error}`;

  return `Primary provider ${formatProviderConfigLabel(primaryProviderConfig)} failed (${reason}). Retried with fallback ${formatProviderConfigLabel(fallbackProviderConfig)}.`;
}

async function getDefaultDisclaimer(locale) {
  const messages = await getMessages(locale);
  const disclaimer = messages?.post?.defaultDisclaimer;

  if (!disclaimer) {
    throw new AiCompositionError(`Locale "${locale}" is missing a default disclaimer.`, {
      status: "missing_default_disclaimer",
      statusCode: 500,
    });
  }

  return disclaimer;
}

async function getSourceConfigs(prisma) {
  const db = await resolvePrismaClient(prisma);

  return db.sourceConfig.findMany({
    orderBy: [{ priority: "asc" }, { sourceType: "asc" }],
    select: {
      allowedDomainsJson: true,
      isEnabled: true,
      name: true,
      notes: true,
      priority: true,
      sourceType: true,
    },
  });
}

async function resolveResearchPayload(request, prisma) {
  const sourceConfigs = await getSourceConfigs(prisma);
  const equipmentIdentity = createCanonicalEquipmentIdentity(request.equipmentName);
  const fixture = getFixtureByNormalizedEquipmentName(equipmentIdentity.normalizedName);

  if (fixture?.researchInput) {
    return {
      fixture,
      researchPayload: buildVerifiedResearchPayload(
        {
          ...fixture.researchInput,
          equipment: {
            aliases: fixture.researchInput.aliases || [],
            name: request.equipmentName,
          },
          equipmentName: request.equipmentName,
          locale: request.locale,
          sourceConfigs,
        },
        {
          now: new Date(),
        },
      ),
    };
  }

  const researchPayload = {
    components: [],
    definition: null,
    equipment: {
      aliases: [],
      locale: request.locale,
      name: request.equipmentName,
      normalizedName: equipmentIdentity.normalizedName,
      slug: equipmentIdentity.slug,
    },
    factClusters: [],
    faults: [],
    maintenanceTasks: [],
    manuals: [],
    manufacturers: [],
    mediaCandidates: [],
    operatingPrinciple: null,
    reliabilityWarnings: [],
    safetyPrecautions: [],
    sourceConfigurations: sourceConfigs.map((config) => ({
      allowedDomains: config.allowedDomainsJson || [],
      isEnabled: config.isEnabled,
      name: config.name,
      notes: config.notes || "",
      priority: config.priority,
      sourceType: config.sourceType,
    })),
    sourceReferences: [],
    uses: [],
    variants: [],
    verification: {
      attributedClusterCount: 0,
      disabledSourceTypes: sourceConfigs.filter((config) => !config.isEnabled).map((config) => config.sourceType),
      isValid: true,
      missingAttributionClusters: [],
    },
  };

  return {
    fixture: null,
    researchPayload,
  };
}

async function buildUniqueEquipmentSlug(tx, baseSlug, equipmentId) {
  const rootSlug = baseSlug || "equipment";
  let slug = rootSlug;
  let suffix = 2;

  while (true) {
    const existingRecord = await tx.equipment.findFirst({
      where: {
        slug,
        ...(equipmentId
          ? {
              NOT: {
                id: equipmentId,
              },
            }
          : {}),
      },
      select: {
        id: true,
      },
    });

    if (!existingRecord) {
      return slug;
    }

    slug = `${rootSlug}-${suffix}`;
    suffix += 1;
  }
}

async function buildUniquePostSlug(tx, baseSlug, postId) {
  const rootSlug = baseSlug || "draft";
  let slug = rootSlug;
  let suffix = 2;

  while (true) {
    const existingRecord = await tx.post.findFirst({
      where: {
        slug,
        ...(postId
          ? {
              NOT: {
                id: postId,
              },
            }
          : {}),
      },
      select: {
        id: true,
      },
    });

    if (!existingRecord) {
      return slug;
    }

    slug = `${rootSlug}-${suffix}`;
    suffix += 1;
  }
}

async function upsertEquipmentRecord(tx, researchPayload) {
  const existingEquipment = await tx.equipment.findUnique({
    where: {
      normalizedName: researchPayload.equipment.normalizedName,
    },
    select: {
      id: true,
      slug: true,
    },
  });
  const equipmentSlug = await buildUniqueEquipmentSlug(
    tx,
    researchPayload.equipment.slug,
    existingEquipment?.id,
  );

  return tx.equipment.upsert({
    where: {
      normalizedName: researchPayload.equipment.normalizedName,
    },
    update: {
      description: researchPayload.definition?.summary || null,
      name: researchPayload.equipment.name,
      slug: existingEquipment?.slug || equipmentSlug,
    },
    create: {
      description: researchPayload.definition?.summary || null,
      name: researchPayload.equipment.name,
      normalizedName: researchPayload.equipment.normalizedName,
      slug: equipmentSlug,
    },
  });
}

async function syncManufacturerAliases(tx, manufacturerId, aliases) {
  const existingAliases = await tx.manufacturerAlias.findMany({
    where: {
      manufacturerId,
    },
    select: {
      normalizedAlias: true,
    },
  });
  const existingAliasSet = new Set(existingAliases.map((alias) => alias.normalizedAlias));

  for (const alias of aliases) {
    const normalizedAlias = alias.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim().replace(/\s+/g, " ");

    if (!normalizedAlias || existingAliasSet.has(normalizedAlias)) {
      continue;
    }

    await tx.manufacturerAlias.create({
      data: {
        alias,
        manufacturerId,
        normalizedAlias,
      },
    });
  }
}

async function upsertManufacturersAndModels(tx, equipmentId, postId, researchPayload) {
  await tx.postManufacturer.deleteMany({
    where: {
      postId,
    },
  });

  for (const manufacturer of researchPayload.manufacturers) {
    const persistedManufacturer = await tx.manufacturer.upsert({
      where: {
        normalizedName_primaryDomain: {
          normalizedName: manufacturer.normalizedName,
          primaryDomain: manufacturer.primaryDomain,
        },
      },
      update: {
        branchCountriesJson: manufacturer.branchCountries?.length ? manufacturer.branchCountries : null,
        headquartersCountry: manufacturer.headquartersCountry || null,
        name: manufacturer.name,
        rankingScore: manufacturer.rankingScore,
        slug: manufacturer.slug,
      },
      create: {
        branchCountriesJson: manufacturer.branchCountries?.length ? manufacturer.branchCountries : null,
        headquartersCountry: manufacturer.headquartersCountry || null,
        name: manufacturer.name,
        normalizedName: manufacturer.normalizedName,
        primaryDomain: manufacturer.primaryDomain,
        rankingScore: manufacturer.rankingScore,
        slug: manufacturer.slug,
      },
    });

    await syncManufacturerAliases(tx, persistedManufacturer.id, manufacturer.aliases);
    await tx.postManufacturer.create({
      data: {
        manufacturerId: persistedManufacturer.id,
        postId,
      },
    });

    for (const model of manufacturer.models || []) {
      await tx.model.upsert({
        where: {
          manufacturerId_slug: {
            manufacturerId: persistedManufacturer.id,
            slug: model.slug,
          },
        },
        update: {
          equipmentId,
          latestKnownYear: model.latestKnownYear,
          name: model.name,
          normalizedName: model.normalizedName,
          rankingScore: model.rankingScore,
          summary: model.summary || null,
        },
        create: {
          equipmentId,
          latestKnownYear: model.latestKnownYear,
          manufacturerId: persistedManufacturer.id,
          name: model.name,
          normalizedName: model.normalizedName,
          rankingScore: model.rankingScore,
          slug: model.slug,
          summary: model.summary || null,
        },
      });
    }
  }
}

async function syncPostStructuredRecords(tx, postId, article) {
  await tx.fault.deleteMany({
    where: {
      postId,
    },
  });
  await tx.maintenanceTask.deleteMany({
    where: {
      postId,
    },
  });

  for (const fault of article.structuredBlocks.faults || []) {
    await tx.fault.create({
      data: {
        cause: fault.cause || "",
        evidenceCount: fault.evidenceCount || 0,
        normalizedTitle: fault.normalizedTitle,
        postId,
        remedy: fault.remedy || "",
        severity: fault.severity,
        sortOrder: fault.sortOrder || 0,
        symptoms: fault.symptoms || "",
        title: fault.title,
      },
    });
  }

  for (const [index, task] of (article.structuredBlocks.maintenanceTasks || []).entries()) {
    await tx.maintenanceTask.create({
      data: {
        description: task.details || "",
        frequency: task.frequency || "Scheduled",
        postId,
        sortOrder: index + 1,
        title: task.label,
      },
    });
  }
}

async function syncSourceReferences(tx, postId, equipmentId, researchPayload) {
  await tx.sourceReference.deleteMany({
    where: {
      postId,
    },
  });

  for (const reference of researchPayload.sourceReferences) {
    if (!reference.url) {
      throw new AiCompositionError(
        `Source reference "${reference.title || reference.sourceDomain || "untitled"}" is missing a canonical URL.`,
        {
          details: {
            reference,
          },
          status: "invalid_research_payload",
          statusCode: 500,
        },
      );
    }

    await tx.sourceReference.create({
      data: {
        accessStatus: reference.accessStatus || null,
        equipmentId,
        excerpt: reference.excerpt || null,
        fileType: reference.fileType || null,
        language: reference.language || null,
        lastCheckedAt: reference.lastCheckedAt ? new Date(reference.lastCheckedAt) : null,
        notes: reference.notes || null,
        postId,
        reliabilityTier: reference.reliabilityTier || null,
        sourceDomain: reference.sourceDomain,
        sourceType: reference.sourceType,
        title: reference.title,
        url: reference.url,
      },
    });
  }
}

function createDuplicateDecisionSnapshot(duplicateCheck) {
  return {
    canonicalEquipment: duplicateCheck.canonicalEquipment,
    duplicateDetected: duplicateCheck.duplicateDetected,
    duplicateMatch: duplicateCheck.duplicateMatch,
    equipment: duplicateCheck.equipment,
    locale: duplicateCheck.locale,
    matchCount: duplicateCheck.matchCount,
  };
}

function createDuplicateBlockedWarning(request, duplicateCheck) {
  const duplicateSlug = duplicateCheck.duplicateMatch?.slug || "existing-post";

  return `Duplicate detection blocked generation for "${request.equipmentName}" in locale "${request.locale}". Existing post slug: ${duplicateSlug}.`;
}

function getSeoRecordDelegate(prisma) {
  return prisma?.sEORecord || prisma?.seoRecord || null;
}

function createDraftPreviewPayload({
  article,
  duplicateCheck,
  persistedDraft,
  providerConfig,
  providerExecutionMode,
  promptBundle,
  request,
  seoPayload,
  warnings,
}) {
  return {
    article: {
      contentHtml: article.contentHtml,
      contentMd: article.contentMd,
      disclaimer: article.disclaimer,
      excerpt: article.excerpt,
      faqJson: article.faq,
      sections: article.sections,
      structuredBlocks: article.structuredBlocks,
      structuredContentJson: article.structuredContentJson,
      title: article.title,
    },
    duplicateCheck: createDuplicateDecisionSnapshot(duplicateCheck),
    editorialStage: persistedDraft.editorialStage,
    locale: request.locale,
    post: {
      id: persistedDraft.postId,
      schedulePublishAt: request.schedulePublishAt,
      translationId: persistedDraft.translationId,
    },
    promptBundle,
    providerConfig: {
      id: providerConfig.id,
      model: providerConfig.model,
      provider: providerConfig.provider,
      purpose: providerConfig.purpose,
    },
    providerExecutionMode,
    seoPayload,
    warnings,
  };
}

async function recordDuplicateBlockedAuditEvent(
  { actorId, duplicateCheck, jobId, request },
  prisma,
) {
  if (!actorId || !duplicateCheck.duplicateMatch) {
    return;
  }

  const db = await resolvePrismaClient(prisma);

  await db.auditEvent.create({
    data: {
      action: "POST_GENERATION_DUPLICATE_BLOCKED",
      actorId,
      entityId: jobId,
      entityType: "generation_job",
      payloadJson: {
        duplicateCheck: createDuplicateDecisionSnapshot(duplicateCheck),
        locale: request.locale,
        replaceExistingPost: false,
      },
    },
  });
}

async function persistDraftPackage(
  { actorId, article, providerConfig, request, researchPayload, seoPayload },
  prisma,
) {
  const db = await resolvePrismaClient(prisma);
  const editorialStage = "GENERATED";

  return db.$transaction(async (tx) => {
    const equipment = await upsertEquipmentRecord(tx, researchPayload);
    const duplicateCheck = await detectDuplicateEquipmentPost(
      {
        equipmentId: equipment.id,
        equipmentName: researchPayload.equipment.name,
        locale: request.locale,
      },
      tx,
    );
    const duplicatePost = duplicateCheck.duplicateMatch;

    if (duplicatePost && !request.replaceExistingPost) {
      throw new AiCompositionError(
        `A non-archived ${request.locale} post already exists for "${request.equipmentName}". Choose replace to update it or cancel to keep the current post unchanged.`,
        {
          details: {
            duplicateCheck: createDuplicateDecisionSnapshot(duplicateCheck),
            duplicateDecision: "replace_required",
          },
          status: "duplicate_post_detected",
          statusCode: 409,
        },
      );
    }

    const canonicalPostSlug = await buildUniquePostSlug(
      tx,
      researchPayload.equipment.slug,
      duplicatePost?.postId,
    );
    const post = duplicatePost
      ? await tx.post.update({
          where: {
            id: duplicatePost.postId,
          },
          data: {
            authorId: actorId,
            editorialStage,
            excerpt: article.excerpt,
            slug: duplicatePost.slug,
            status: PostStatus.DRAFT,
          },
        })
      : await tx.post.create({
          data: {
            authorId: actorId,
            editorialStage,
            equipmentId: equipment.id,
            excerpt: article.excerpt,
            slug: canonicalPostSlug,
            status: PostStatus.DRAFT,
          },
        });

    const translation = await tx.postTranslation.upsert({
      where: {
        postId_locale: {
          locale: request.locale,
          postId: post.id,
        },
      },
      update: {
        contentHtml: article.contentHtml,
        contentMd: article.contentMd,
        disclaimer: article.disclaimer,
        excerpt: article.excerpt,
        faqJson: toSerializableJson(article.faq),
        isAutoTranslated: false,
        structuredContentJson: toSerializableJson(article.structuredContentJson),
        title: article.title,
      },
      create: {
        contentHtml: article.contentHtml,
        contentMd: article.contentMd,
        disclaimer: article.disclaimer,
        excerpt: article.excerpt,
        faqJson: toSerializableJson(article.faq),
        isAutoTranslated: false,
        locale: request.locale,
        postId: post.id,
        structuredContentJson: toSerializableJson(article.structuredContentJson),
        title: article.title,
      },
    });

    const seoRecordDelegate = getSeoRecordDelegate(tx);

    if (!seoRecordDelegate) {
      throw new AiCompositionError("The Prisma SEO record delegate is unavailable.", {
        status: "internal_error",
        statusCode: 500,
      });
    }

    await seoRecordDelegate.upsert({
      where: {
        postTranslationId: translation.id,
      },
      update: {
        authorsJson: toSerializableJson(seoPayload.authors),
        canonicalUrl: seoPayload.canonicalUrl,
        keywordsJson: toSerializableJson(seoPayload.keywords),
        metaDescription: seoPayload.metaDescription,
        metaTitle: seoPayload.metaTitle,
        noindex: seoPayload.noindex,
        ogDescription: seoPayload.ogDescription,
        ogImageId: seoPayload.ogImageId,
        ogTitle: seoPayload.ogTitle,
        twitterDescription: seoPayload.twitterDescription,
        twitterTitle: seoPayload.twitterTitle,
      },
      create: {
        authorsJson: toSerializableJson(seoPayload.authors),
        canonicalUrl: seoPayload.canonicalUrl,
        keywordsJson: toSerializableJson(seoPayload.keywords),
        metaDescription: seoPayload.metaDescription,
        metaTitle: seoPayload.metaTitle,
        noindex: seoPayload.noindex,
        ogDescription: seoPayload.ogDescription,
        ogImageId: seoPayload.ogImageId,
        ogTitle: seoPayload.ogTitle,
        postTranslationId: translation.id,
        twitterDescription: seoPayload.twitterDescription,
        twitterTitle: seoPayload.twitterTitle,
      },
    });

    await syncPostStructuredRecords(tx, post.id, article);
    await upsertManufacturersAndModels(tx, equipment.id, post.id, researchPayload);
    await syncSourceReferences(tx, post.id, equipment.id, researchPayload);

    if (duplicatePost && request.replaceExistingPost) {
      await tx.auditEvent.create({
        data: {
          action: "POST_DUPLICATE_REPLACED",
          actorId,
          entityId: post.id,
          entityType: "post",
          payloadJson: {
            duplicateCheck: createDuplicateDecisionSnapshot(duplicateCheck),
            locale: request.locale,
            providerConfigId: providerConfig.id,
            slug: post.slug,
          },
        },
      });
    }

    await tx.auditEvent.create({
      data: {
        action: "POST_GENERATED",
        actorId,
        entityId: post.id,
        entityType: "post",
        payloadJson: {
          locale: request.locale,
          providerConfigId: providerConfig.id,
          slug: post.slug,
        },
      },
    });

    return {
      editorialStage,
      postId: post.id,
      translationId: translation.id,
    };
  });
}

export async function composeDraftPackage(input, options = {}, prisma) {
  const requestedProviderConfig =
    options.providerConfig || (await resolveProviderConfig(input.providerConfigId, prisma));
  const promptLayers = options.promptLayers || (await loadActivePromptLayers(prisma));
  const disclaimer = options.disclaimer || (await getDefaultDisclaimer(input.locale));
  const fixtureResolution = options.fixtureResolution || (await resolveResearchPayload(input, prisma));
  const preCompositionPromptBundle = buildPromptBundle({
    disclaimer,
    promptLayers,
    request: input,
    researchPayload: fixtureResolution.researchPayload,
  });
  let providerConfig = requestedProviderConfig;
  let provider;
  let providerResult;
  let structuredArticle;

  async function composeWithProviderConfig(activeProviderConfig) {
    try {
      const activeProvider = createProvider(activeProviderConfig, options.providerOptions);
      const activeProviderResult = await activeProvider.composeStructuredArticle({
        disclaimer,
        fixture: fixtureResolution.fixture,
        promptBundle: preCompositionPromptBundle,
        providerConfig: activeProviderConfig,
        request: {
          ...input,
          disclaimer,
        },
        researchPayload: fixtureResolution.researchPayload,
      });
      const structuredArticle = activeProviderResult.structuredArticle;

      validateStructuredArticle(structuredArticle);

      return {
        provider: activeProvider,
        providerConfig: activeProviderConfig,
        providerResult: activeProviderResult,
        structuredArticle,
      };
    } catch (error) {
      throw normalizeProviderCompositionError(error, activeProviderConfig);
    }
  }

  let fallbackWarning = null;

  try {
    ({ provider, providerConfig, providerResult, structuredArticle } = await composeWithProviderConfig(
      requestedProviderConfig,
    ));
  } catch (error) {
    const fallbackProviderConfig = await findFallbackProviderConfig(prisma, requestedProviderConfig.id);

    if (!fallbackProviderConfig) {
      throw error;
    }

    ({ provider, providerConfig, providerResult, structuredArticle } = await composeWithProviderConfig(
      fallbackProviderConfig,
    ));
    fallbackWarning = createProviderFallbackWarning(
      requestedProviderConfig,
      fallbackProviderConfig,
      error,
    );
  }
  const promptBundle = buildPromptBundle({
    article: structuredArticle,
    disclaimer,
    promptLayers,
    request: input,
    researchPayload: fixtureResolution.researchPayload,
  });

  const markdown = buildMarkdownFromStructuredArticle(structuredArticle);
  const html = buildHtmlFromStructuredArticle(structuredArticle);
  const articleWithArtifacts = {
    ...structuredArticle,
    contentHtml: html,
    contentMd: markdown,
    faq: structuredArticle.faq,
    structuredContentJson: {
      promptBundle,
      provider: {
        executionMode: providerResult.executionMode,
        model: provider.model,
        name: provider.name,
      },
      renderArtifacts: {
        html: true,
        markdown: true,
      },
      sections: structuredArticle.sections,
      structuredBlocks: structuredArticle.structuredBlocks,
      warnings: fixtureResolution.researchPayload.reliabilityWarnings,
    },
  };
  let seoPayload;

  try {
    seoPayload = buildSeoPayload(articleWithArtifacts, {
      locale: input.locale,
    });
  } catch (error) {
    await recordObservabilityEvent(
      {
        action: "SEO_FAILURE",
        entityId: input.equipmentName || input.locale,
        entityType: "seo_generation",
        error,
        message: `SEO payload generation failed for "${input.equipmentName}" in locale "${input.locale}".`,
        payload: {
          locale: input.locale,
          providerConfigId: providerConfig.id,
          stage: "seo_generation",
        },
      },
      prisma,
    ).catch(() => {});

    throw error;
  }

  return {
    article: articleWithArtifacts,
    promptBundle,
    providerConfig,
    providerExecutionMode: providerResult.executionMode,
    researchPayload: fixtureResolution.researchPayload,
    seoPayload,
    warnings: dedupeStrings([
      fallbackWarning,
      ...fixtureResolution.researchPayload.reliabilityWarnings,
    ]),
  };
}

export async function generateDraftFromRequest(input, options = {}, prisma) {
  const {
    cancelGenerationJob,
    completeGenerationJob,
    createGenerationJobRecord,
    failGenerationJob,
    markGenerationJobRunning,
  } = await import("@/lib/jobs");
  const providerConfig = await resolveProviderConfig(input.providerConfigId, prisma);
  const duplicateCheck = await detectDuplicateEquipmentPost(
    {
      equipmentName: input.equipmentName,
      locale: input.locale,
    },
    prisma,
  );
  const job = await createGenerationJobRecord(
    {
      actorId: options.actorId,
      currentStage: generationStageOrder[0],
      equipmentName: input.equipmentName,
      locale: input.locale,
      providerConfigId: providerConfig.id,
      replaceExistingPost: input.replaceExistingPost,
      requestJson: input,
      schedulePublishAt: input.schedulePublishAt ? new Date(input.schedulePublishAt) : null,
      status: "PENDING",
    },
    prisma,
  );
  let jobFinalized = false;

  try {
    await markGenerationJobRunning(job.id, generationStageOrder[0], prisma);

    if (duplicateCheck.duplicateDetected && !input.replaceExistingPost) {
      const duplicateDecision = createDuplicateDecisionSnapshot(duplicateCheck);
      const blockedWarning = createDuplicateBlockedWarning(input, duplicateCheck);

      await cancelGenerationJob(
        job.id,
        {
          actorId: options.actorId,
          currentStage: generationTerminalStageIds.duplicateCheckBlocked,
          postId: duplicateCheck.duplicateMatch?.postId || null,
          responseJson: {
            duplicateCheck: duplicateDecision,
            duplicateDecision: "replace_required",
          },
          warningJson: [blockedWarning],
        },
        prisma,
      );
      jobFinalized = true;

      await recordDuplicateBlockedAuditEvent(
        {
          actorId: options.actorId,
          duplicateCheck,
          jobId: job.id,
          request: input,
        },
        prisma,
      );

      throw new AiCompositionError(
        `A non-archived ${input.locale} post already exists for "${input.equipmentName}". Choose replace to update it or cancel to keep the current post unchanged.`,
        {
          details: {
            duplicateCheck: duplicateDecision,
            duplicateDecision: "replace_required",
            jobId: job.id,
          },
          status: "duplicate_post_detected",
          statusCode: 409,
        },
      );
    }

    await markGenerationJobRunning(job.id, generationStageOrder[1], prisma);

    const composed = await composeDraftPackage(
      input,
      {
        ...options,
        providerConfig,
      },
      prisma,
    );

    await markGenerationJobRunning(job.id, generationStageOrder[2], prisma);

    const persistedDraft = await persistDraftPackage(
      {
        actorId: options.actorId,
        article: composed.article,
        providerConfig: composed.providerConfig,
        request: input,
        researchPayload: composed.researchPayload,
        seoPayload: composed.seoPayload,
      },
      prisma,
    );

    await completeGenerationJob(
      job.id,
      {
        actorId: options.actorId,
        currentStage: generationStageOrder[3],
        postId: persistedDraft.postId,
        providerConfigId: composed.providerConfig.id,
        responseJson: {
          duplicateCheck: createDuplicateDecisionSnapshot(duplicateCheck),
          duplicateDecision: duplicateCheck.duplicateDetected ? "replace_existing" : "create_new",
          promptBundle: composed.promptBundle,
          providerExecutionMode: composed.providerExecutionMode,
          seoPayload: composed.seoPayload,
          structuredContentJson: composed.article.structuredContentJson,
        },
        warningJson: composed.warnings,
      },
      prisma,
    );

    return {
      editorialStage: persistedDraft.editorialStage,
      jobId: job.id,
      postId: persistedDraft.postId,
      status: "draft_saved",
      success: true,
      preview: createDraftPreviewPayload({
        article: composed.article,
        duplicateCheck,
        persistedDraft,
        providerConfig: composed.providerConfig,
        providerExecutionMode: composed.providerExecutionMode,
        promptBundle: composed.promptBundle,
        request: input,
        seoPayload: composed.seoPayload,
        warnings: composed.warnings,
      }),
      warnings: composed.warnings,
    };
  } catch (error) {
    if (!jobFinalized) {
      await failGenerationJob(
        job.id,
        error,
        {
          actorId: options.actorId,
          currentStage: generationTerminalStageIds.failed,
        },
        prisma,
      ).catch(() => {});
    }
    throw error;
  }
}

export function createAiCompositionErrorPayload(error) {
  if (!(error instanceof AiCompositionError)) {
    console.error(error);
  }

  const normalizedError =
    error instanceof AiCompositionError
      ? error
      : new AiCompositionError("An unexpected draft generation error occurred.", {
          details:
            error instanceof Error
              ? {
                  errorName: error.name,
                }
              : undefined,
          status: "internal_error",
          statusCode: 500,
        });

  return {
    body: {
      details: normalizedError.details || undefined,
      message: normalizedError.message,
      status: normalizedError.status,
      success: false,
    },
    statusCode: normalizedError.statusCode,
  };
}
